/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IDropAreaConfig,
} from './interfaces/drop-area';

export namespace Components {
  interface DropArea {
    'config': IDropAreaConfig;
  }
  interface DropElement {
    'file': any;
  }
  interface LoaderError {}
  interface LoaderPending {}
  interface LoaderSuccess {}
}

declare global {


  interface HTMLDropAreaElement extends Components.DropArea, HTMLStencilElement {}
  var HTMLDropAreaElement: {
    prototype: HTMLDropAreaElement;
    new (): HTMLDropAreaElement;
  };

  interface HTMLDropElementElement extends Components.DropElement, HTMLStencilElement {}
  var HTMLDropElementElement: {
    prototype: HTMLDropElementElement;
    new (): HTMLDropElementElement;
  };

  interface HTMLLoaderErrorElement extends Components.LoaderError, HTMLStencilElement {}
  var HTMLLoaderErrorElement: {
    prototype: HTMLLoaderErrorElement;
    new (): HTMLLoaderErrorElement;
  };

  interface HTMLLoaderPendingElement extends Components.LoaderPending, HTMLStencilElement {}
  var HTMLLoaderPendingElement: {
    prototype: HTMLLoaderPendingElement;
    new (): HTMLLoaderPendingElement;
  };

  interface HTMLLoaderSuccessElement extends Components.LoaderSuccess, HTMLStencilElement {}
  var HTMLLoaderSuccessElement: {
    prototype: HTMLLoaderSuccessElement;
    new (): HTMLLoaderSuccessElement;
  };
  interface HTMLElementTagNameMap {
    'drop-area': HTMLDropAreaElement;
    'drop-element': HTMLDropElementElement;
    'loader-error': HTMLLoaderErrorElement;
    'loader-pending': HTMLLoaderPendingElement;
    'loader-success': HTMLLoaderSuccessElement;
  }
}

declare namespace LocalJSX {
  interface DropArea extends JSXBase.HTMLAttributes<HTMLDropAreaElement> {
    'config'?: IDropAreaConfig;
  }
  interface DropElement extends JSXBase.HTMLAttributes<HTMLDropElementElement> {
    'file'?: any;
  }
  interface LoaderError extends JSXBase.HTMLAttributes<HTMLLoaderErrorElement> {}
  interface LoaderPending extends JSXBase.HTMLAttributes<HTMLLoaderPendingElement> {}
  interface LoaderSuccess extends JSXBase.HTMLAttributes<HTMLLoaderSuccessElement> {}

  interface IntrinsicElements {
    'drop-area': DropArea;
    'drop-element': DropElement;
    'loader-error': LoaderError;
    'loader-pending': LoaderPending;
    'loader-success': LoaderSuccess;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


